formatter: "" # this is required

version: ""

#header-from: ""
#footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}
  
  ## Prerequisites
  
  The following IAM policy needs to be attached to the role that is assumed during the creation of module resources:
  
  ```json
  {{ include "iam/vault-policy.json" }}
  ```
  
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Modules  }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false


sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true